---
name: "Publish Python Package"

on:
  release:
    types: ["published"]

permissions:
  contents: "read"

jobs:
  publish_gh:
    name: "Publish to GitHub"
    runs-on: "ubuntu-22.04"
    env:
      INVOKE_NAUTOBOT_SSOT_UNIFI_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "Install Python Packages"
        run: "pip install poetry"
      - name: "Set env"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Run Poetry Version"
        run: "poetry version $RELEASE_VERSION"
      - name: "Install Dependencies (needed for mkdocs)"
        run: "poetry install --no-root"
      - name: "Build Documentation"
        run: "poetry run invoke build-and-check-docs"
      - name: "Run Poetry Build"
        run: "poetry build"
      - name: "Upload binaries to release"
        uses: "svenstaro/upload-release-action@v2"
        with:
          file: "dist/*"
          tag: "${{ github.ref }}"
          overwrite: true
          file_glob: true
  publish_pypi:
    runs-on: "ubuntu-latest"
    environment: "publish"
    permissions:
      id-token: "write"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Set up Python"
        uses: "actions/setup-python@v3"
        with:
          python-version: "3.x"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: "Set env"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Run Poetry Version"
        run: "poetry version $RELEASE_VERSION"
      - name: "Run Poetry Build"
        run: "poetry build"
      - name: "Publish package"
        uses: "pypa/gh-action-pypi-publish@release/v1"
